name: ReleaseLibraries

on:
  push:
      branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ARTIFACTORY_USERNAME: "sreenivasrao.basi@ingka.com"
  ARTIFACTORY_PASSWORD: "In" 
  #${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
  ARTIFACTORY_HOST: "https://artifactory.build.ingka.ikea.com:443/artifactory/ilo-fli-common-maven-release-local"
  ARTIFACT_VERSION: "1.0.2"
  ARTIFACTORY_LOCAL: "https://artifactory.build.ingka.ikea.com:443/artifactory/ilo-fli-common-maven-release-local"
  ARTIFACTORY_PATH: "com/test_artfct/jar"
  VERSION_TYPE: "SNAPSHOT"
  COMMITMESSAGE: ${{ github.event.head_commit.message }}

jobs:

  ReleaseLibraries-Job:
    #runs-on: ubuntu-22.04.1
    runs-on: ubuntu-latest
    steps:
      - name: Validate input commit message
        run: |
          message=${{ contains(github.event.head_commit.message, 'Release Library') }}
          if [ ${message} == false ]; then
            echo "Invalid commit message, Please use 'Release Library' to run job "
            exit -1
          fi
          echo "Commit message is validated"
      - name: Checkout branch from GitHub
        uses: actions/checkout@v3

      - name: Setting up variables
        run: |
          echo "WORK_DIR=`pwd`" >> $GITHUB_ENV
      - name: Validating of .bom file
        #id: validation
        run: |
          for i in *.bom
          do
          echo "file name :" $i
          done
          #while IFS="" read -r line;
          #do
              #echo $line
              #if [ ${line} < 0 ]; then
                #echo "Input value is  null"
                #exit -1
              #fi
          #done < ./sample.bom
          echo "bom file is available and valid" $i

      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'maven'

      - name: GitHub Actions Build with Maven
        run: |
          #mvn -B package --file pom.xml
          mvn -U ./settings.xml package -Dmaven.test.skip -Drevision=${{env.ARTIFACT_VERSION}}
      
      - name: Set up Cache for Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
