name: ReleaseLibraries

on:
  push:
      branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  COMMITMESSAGE: ${{ github.event.head_commit.message }}

jobs:

  validate-input:
    #runs-on: ubuntu-22.04.1
    runs-on: ubuntu-latest
    steps:
      - name: Validate input commit message
        run: |
          message=${{ contains(github.event.head_commit.message, 'Release Library') }}
          if [ ${message} == false ]; then
            echo "Invalid commit message, Please use 'Release Library' to run job "
            exit -1
          fi
          echo "Commit message is validated"
      - name: Checkout branch from GitHub
        uses: actions/checkout@v3

      - name: Setting up variables
        run: |
          echo "WORK_DIR=`pwd`" >> $GITHUB_ENV
      - name: Validating of .bom file
        #id: validation
        run: |
          for i in *.bom
          do
          echo "file name :" $i
          done
          #while IFS="" read -r line;
          #do
              #echo $line
              #if [ ${line} < 0 ]; then
                #echo "Input value is  null"
                #exit -1
              #fi
          #done < ./sample.bom
          echo "bom file is available and valid" $i
