name: ReleaseLibraries

on:
  push:
      branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  COMMITMESSAGE: ${{ github.event.head_commit.message }}

jobs:


  validate-input:
    runs-on: ubuntu-latest
    steps:
      - name: Validate input
        run: |
          message=${{ contains(github.event.head_commit.message, 'Release Library') }}
          if [ ${message} == false ]; then
            echo "Invalid commit message, Please use 'Release Library' to  run job "
            exit -1
          fi
          echo "Commit message is validated"
      - name: Setting variables
        run: |
          echo "WORK_DIR=`pwd`" >> $GITHUB_ENV
      - name: Validating of .bom file
        run: |
          for i in *.bom
          do
            echo "file name :" $i
          done
          echo "bom file is available and valid" $i
